name: test
on: push

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # container: node:20-bookworm-slim

    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    env:
      CLUE_TEST_DB_HOST: localhost
      CLUE_TEST_DB: postgres
      CLUE_TEST_DB_USER: postgres
      CLUE_TEST_DB_PWD: postgres

      CLUE_DB_HOST: localhost
      CLUE_DB: postgres
      CLUE_DB_USER: postgres
      CLUE_DB_PWD: postgres

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.x"
      - name: Install app
        run: pip install .
      - name: Install Yoyo-migrations
        run: pip install yoyo-migrations
      - name: Run application migrations
        run: yoyo apply
      - name: Extract test input file
        run: tar -xf tests/data/sales_data_medium.tgz -C tests/data/
      - name: Import test data
        run: clue import-data --csv_path tests/data/sales_data_medium.csv -t sales_report
      - name: Run integration tests
        run: pytest -m integration
